# This file describes a conda environment that can be to install samos
#
# Run the following command to set up this environment:
# $ conda env create -f samos_env.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f samos_env.yml
#
# Run the following command to activate the environment:
# $ conda activate samos
#
# To deactivate the environment run the following command:
# $ conda deactivate
#
# To remove the environment entirely, run the following command:
# $ conda env remove -n samos

name: samos

channels:
  - conda-forge
  - defaults

dependencies:
  - python==3.12
  - pip

  - pip:
    - matplotlib==3.8.3
    # REVISIT: Once aplpy doesn't depend on astropy.configuration.update_default_config
    - astropy==5.3.4
    - photutils==1.11.0
    - ginga==4.1.1
    - astroquery==0.4.6
    - numpy==1.26.4
    - pandas==2.2.0
    - aplpy==2.1.0
    - regions==0.8
    - tksheet==7.0.5
    - twirl==0.4.2
    - ttkbootstrap==1.10.1

    # Current package
    - -e .
