#!/usr/bin/env python
"""
Command-line command utility to start up the SAMOS gui (intended for use, especially, once
we actually start installing the SAMOS module with pip)

Authors
-------

    - Brian York (york@stsci.edu)

Use
---

    This module is intended to be run from the command line. It currently does not take
    any arguments.

Dependencies
------------
    
    The samos module must be installed using pip.

"""

from samos.SAMOS_New_SHIPPED import run_samos

def main_fn():
    run_samos()

if __name__ == "__main__":
    main_fn()
