#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 11 14:03:54 2022

@author: robberto
"""
    
import math
import pathlib

def convertSIlly(fname, outname=None):
    FITSblock = 2880

    # If no output file given, just prepend "fixed"
    if outname is None:
        fname = pathlib.Path(fname)
        dd = fname.parent
        outname = pathlib.Path(fname.parent, 'fixed'+fname.name)
    
    with open(fname, "rb") as in_f:
        buf = in_f.read()

    # Two fixes:
    # Header cards:
    buf = buf.replace(b'SIMPLE  =                    F', b'SIMPLE  =                    T')
    buf = buf.replace(b'BITPIX  =                  -16', b'BITPIX  =                   16')
    buf = buf.replace(b"INSTRUME= Spectral Instruments, Inc. 850-406 camera  ", b"INSTRUME= 'Spectral Instruments, Inc. 850-406 camera'")
    
    # Pad to full FITS block:
    blocks = len(buf) / FITSblock
    pad = round((math.ceil(blocks) - blocks) * FITSblock)
    buf = buf + (b'\0' * pad)
    
    with open(outname, "wb+") as out_f:
        out_f.write(buf)
        
convertSIlly("/Users/robberto/Box/@Massimo/_Python/SAMOS_GUI_dev/fits_image/newimage.fit","/Users/robberto/Box/@Massimo/_Python/SAMOS_GUI_dev/fits_image/newimage_out.fit")