from .ccd import CCDPage
from .ccd2dmd import CCD2DMDPage
from .config import ConfigPage
from .dmd import DMDPage
from .etc import ETCPage
from .gs import GSPage
from .main_page import MainPage
from .motors import MotorsPage
from .soar import SOARPage
