#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  6 12:27:12 2022

@author: robberto
"""

from html.parser import HTMLParser
import urllib.request as urllib2

class MyHTMLParser(HTMLParser):

   #Initializing lists
   lsStartTags = list()
   lsEndTags = list()
   lsStartEndTags = list()
   lsComments = list()

   #HTML Parser Methods
   def handle_starttag(self, startTag, attrs):
       self.lsStartTags.append(startTag)

   def handle_endtag(self, endTag):
       self.lsEndTags.append(endTag)

   def handle_startendtag(self,startendTag, attrs):
       self.lsStartEndTags.append(startendTag)

   def handle_comment(self,data):
       self.lsComments.append(data)

#creating an object of the overridden class
parser = MyHTMLParser()

#Opening NYTimes site using urllib2
#html_page = html_page = urllib2.urlopen("https://www.nytimes.com/")
html_page = urllib2.urlopen('http://128.220.146.254:8900/')

#Feeding the content
parser.feed(str(html_page.read()))

#printing the extracted values
#print("Start tags", parser.lsStartTags)
#print("End tags", parser.lsEndTags)
#print("Start End tags", parser.lsStartEndTags)
#print("Comments", parser.lsComments)

import pandas as pd
import requests
url = 'http://128.220.146.254:8900/'
html_string = requests.get(url)
string =  html_string.content.decode() 
print(string)
dfs = pd.read_html(string)
df = dfs[0]  # pd.read_html reads in all tables and returns a list of DataFrames
print(dfs)


import requests

xml = """<?xml version='1.0' encoding='utf-8'?>
<a>б</a>"""
headers = {'Content-Type': '/setup.htm'} # set what your server accepts
print(requests.post(url, data=xml, headers=headers).text)
